<?php

/**
 * @file
 * Short file description here.
 *
 * Long description here.
 */

module_load_include('inc', 'islandora', 'includes/solution_packs');

/**
 * Implements hook_menu().
 */
function ems_menu() {

  $items = array();
  $items['ems/get_collation'] = array(
    'title' => 'Get TEI Datastreams',
    'description' => 'Get TEI Datastreams',
    'page callback' => 'getTEIDatastream',
    'access callback' => TRUE,
    'file' => 'includes/EMSController.php',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function ems_help($path, $arg) {

  switch ($path) {
    case 'admin/help#ens':

      // Return a line-break version of the README.
      $readme = file_get_contents(drupal_get_path('module', 'ems') . '/README.md');
      return nl2br($readme);
  }
}

/**
 * Send Object info to js for reference
 */
function ems_islandora_view_object(AbstractObject $object) {
  $pid = "unknown";
  if (isset($object)) {
    $pid = $object->id;
  }

  drupal_add_js(array('islandora_ems' =>
    array('pid' => $pid
    )
  ), array('type' => 'setting')
  );
}

function ems_preprocess_node(&$variables) {
  drupal_add_css('https://fonts.googleapis.com/css?family=Roboto:300,400,500', array('type' => 'external'));
  drupal_add_css('https://fonts.googleapis.com/icon?family=Material+Icons', array('type' => 'external'));
}

